# Generated by Django 5.2.14 on 2026-06-03 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('reason', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('tmdb_id', models.IntegerField()),
                ('season_number', models.IntegerField(default=0)),
                ('episode_number', models.IntegerField(default=0)),
                ('rating', models.FloatField()),
                ('rby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottratings.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('tmdb_id', models.IntegerField()),
                ('season_number', models.IntegerField(default=0)),
                ('episode_number', models.IntegerField(default=0)),
                ('c', models.TextField(max_length=150)),
                ('cat', models.DateTimeField(auto_now_add=True)),
                ('cby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottratings.users')),
            ],
        ),
    ]
